### PR TITLE
docs: Fix page ordering

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by cgwalters** [comment]
What this one will likely hit is the markdown linter versus the `nav_order` requirement

**Comment by cgwalters** [comment]
Yeah my vote is to just remove pre-commit because the markdown linter is very aggressive and definitely in that "finds 5% of real issues, 95% noise" space.

**Comment by lmilbaum** [comment]
> Yeah my vote is to just remove pre-commit because the markdown linter is very aggressive and definitely in that "finds 5% of real issues, 95% noise" space.

We can remove the check all together or tweak the markdown linter to skip this error.

**Pull request merged**
